adicionando personas
Interacao-Humano-Computador/2023.1-Wikipedia pull request #34
Opened 2023-05-01 00:27 UTC by LucasLopesFrazao

## Descrição 

Adicionando as 3 personas e a antipersona

## Issues

resolve #33

2023-05-01 01:09 UTC, analuizargds requested changes
ortografia na área de tarefas da tabela 1

2023-05-01 01:12 UTC, analuizargds requested changes
- Ortografia na área de habilidades da tabela 3
- Na descrição da tabela 4 "antipersona" está escrito diferente da área status da tabela 4. Melhor padronizar como "antipersona"
- O texto da área objetivos da tabela 4 foge do tema

2023-05-01 14:18 UTC, oo7gabriel approved these changes
Assim que adicionada as alterações pedidas pela revisora Ana, acredito que esteja tudo certo !

2023-05-06 22:52 UTC, analuizargds requested changes
- Em endereço na tabela do luís está escrito lude
- Em endereço na tabela de Maria Luiza está escrito Antonia
- Em tarefas da tabela do Rodrigo está escrito Paulo
- Em endereço e locomoção de Nelson está escrito Wellington
- Os nomes dos arquivos de imagens ainda são os nomes antigos das personas

2023-05-07 20:46 UTC, analuizargds approved these changes
aprovado

2023-05-07 20:47 UTC, merged