45-adicionando estrutura geral do projeto
Interacao-Humano-Computador/2023.1-Wikipedia pull request #46
Opened 2023-05-13 17:04 UTC by chaydson

## Descrição 
resolve #45

2023-05-14 15:10 UTC, analuizargds requested changes
- Na Introdução "projetada" está escrito duas vezes.
- No Objetivo está escrito "Neste resistente". É isso mesmo? Se for então não precisa de correção.
- Na parte Criação de Artigo não seria melhor trocar a palavra "apresentações" por "conteúdos" ou "temas" ou algo do tipo?
- Na parte Limitações e Características Negativas onde fala que o usuário precisa decorar um caminho tá meio confuso. Acho que tem algo repetido que tem que retirar.

Após feita as alterações o PR está aprovado

2023-05-15 03:52 UTC, chaydson commented
> * No Objetivo está escrito "Neste resistente". É isso mesmo? Se for então não precisa de correção.

não achei isso no texto

2023-05-15 03:55 UTC, chaydson commented
> * Na parte Criação de Artigo não seria melhor trocar a palavra "apresentações" por "conteúdos" ou "temas" ou algo do tipo?

também não achei essa palavra no texto

2023-05-16 00:14 UTC, analuizargds approved these changes
aprovado

2023-05-16 00:20 UTC, merged