53 planejamento avaliacao storyboard
Interacao-Humano-Computador/2023.1-Wikipedia pull request #54
Opened 2023-05-19 00:31 UTC by analuizargds

## Descrição 
Adiciona página de planejamento da avaliação do storyboard

## Issues
resolve #53

2023-05-20 12:56 UTC, LucasLopesFrazao approved these changes
:+1:

2023-05-23 00:14 UTC, chaydson requested changes

2023-05-23 00:14 UTC, chaydson commented on docs/design-avaliacao-desenvolvimento/nivel1/storyboard/planejamentoDaAvaliacao.md
> +Abaixo, apresentamos a Tabela 1 com o cronograma da avaliação:
remover abaixo

2023-05-23 00:14 UTC, chaydson commented on docs/design-avaliacao-desenvolvimento/nivel1/storyboard/planejamentoDaAvaliacao.md
> +Abaixo, encontra-se o Termo de Consentimento que será assinado antes da realização da entrevista, como parte do processo necessário para obter a permissão do participante.
remover abaixo

2023-05-23 00:14 UTC, chaydson commented on docs/design-avaliacao-desenvolvimento/nivel1/storyboard/planejamentoDaAvaliacao.md
> +No contexto da atividade de [Perfil do Usuário](../../../analise-de-requisitos/perfilDeUsuario.md) e das [Personas](../../../analise-de-requisitos/personas.md), podemos identificar as qualidades nece
académicos deveria ser acadêmicos

2023-05-23 00:20 UTC, chaydson approved these changes
top

2023-05-23 00:24 UTC, merged