Como utilizar o guia de estilo
Interacao-Humano-Computador/2023.1-Wikipedia pull request #55
Opened 2023-05-20 13:06 UTC by LucasLopesFrazao

## Descrição 

## Issues

2023-05-21 20:07 UTC, oo7gabriel approved these changes
Aprovado !

2023-05-21 20:45 UTC, SamuelGSouza commented
Por favor, crie uma nova issue para acompanhar esse pull request e garantir a conformidade com os padrões estabelecidos.

2023-05-21 21:51 UTC, SamuelGSouza requested changes
Por favor, crie uma nova issue para acompanhar esse pull request e garantir a conformidade com os padrões estabelecidos.

2023-05-22 23:04 UTC, SamuelGSouza approved these changes
:+1:

2023-05-22 23:04 UTC, merged